telegram:
  phone_number: "+1234567890"          # Your Telegram phone number in international format
  api_id: 123456                        # Your Telegram API ID (integer)
  api_hash: "your_telegram_api_hash"    # Your Telegram API Hash (string)
  password: "your_2FA_password"         # Your Telegram account password (if 2FA is enabled)

download:
  base_dir: "tmd"  # Absolute or relative path where media will be downloaded

logging:
  filename: "app.logger"       # Log file name (can include path)
  max_size: 10              # Maximum size in megabytes before logger rotation occurs
  max_age: 28               # Maximum number of days to retain old logger files
  max_backups: 5            # Maximum number of old logger files to keep
  compress: true            # Whether to compress rotated logger files
  level: "info"             # Logging level

fetching:
  dialogs_limit: 100        # Maximum number of dialogs to fetch in one request
  messages_limit: 50        # Maximum number of messages to fetch per dialog

minio:
  endpoint: "localhost:9000"         # Host and port where MinIO is accessible
  access_key: "localuser"            # MinIO root user (matches MINIO_ROOT_USER)
  secret_key: "localpass"            # MinIO root password (matches MINIO_ROOT_PASSWORD)
  bucket: "tmd"                      # Name of the bucket to store media files
  base_path: "me"                    # An optional folder path (prefix) within the bucket
  use_ssl: false                     # Whether to connect via HTTPS (true) or HTTP (false)

database:
  dialect: "postgres"                   # Database dialect
  host: "localhost"                     # Database host
  port: 5432                            # Database port
  user: "your_db_user"                  # Database user
  password: "your_db_password"          # Database password
  dbname: "your_db_name"                # Database name
  sslmode: "disable"                    # SSL mode