version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER:-localuser}"
      POSTGRES_PASSWORD: "${DB_PWD:-localpass}"
      POSTGRES_DB: "${DB_NAME:-localdb}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER:-localuser}"
      MINIO_ROOT_PASSWORD: "${MINIO_PWD:-localpass}"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  create_buckets:
    container_name: minio_create_buckets
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      /usr/bin/mc config host add localminio http://minio:9000 ${MINIO_USER:-localuser} ${MINIO_PWD:-localpass};
      /usr/bin/mc mb localminio/tmd;
      /usr/bin/mc anonymous set download localminio/tmd;
      /usr/bin/mc ls localminio;
      exit 0;
      "
    profiles: ["init"]

volumes:
  postgres_data:
  minio_data:
